packages:
  - internal/*
  - internal/lint-configs/*
  - 'packages/*'
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - apps/*
  - scripts/*
  - docs
catalog:
  '@changesets/git': ^3.0.2
  '@manypkg/get-packages': ^2.2.2
  '@vue/shared': ^3.5.13
  '@vueuse/core': ^12.0.0
  cac: ^6.7.14
  chalk: ^5.3.0
  consola: ^3.2.3
  cross-env: ^7.0.3
  dayjs: ^1.11.13
  defu: ^6.1.4
  execa: ^9.5.2
  find-up: ^7.0.0
  ora: ^8.1.1
  pkg-types: ^1.2.1
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  rimraf: ^6.0.1
  rollup: ^4.28.1
  vite: ^6.0.3
  vue: '^3.5.13'
  vue-router: ^4.5.0
