packages:
  - internal/*
  - internal/lint-configs/*
  - "packages/*"
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - apps/*
  - scripts/*
  - docs
catalog:
  '@vue/shared': ^3.5.13
  '@vueuse/core': ^12.0.0
  defu: ^6.1.4
  vite: ^6.0.3
  vue: "^3.5.13"
  vue-router: ^4.5.0
